//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TelephoneDirectory
{
    using System;
    using System.Collections.Generic;
    
    public partial class Directory
    {
        public int Code { get; set; }
        public string NameOrg { get; set; }
        public string Phone { get; set; }
        public string AddressOrg { get; set; }
        public string TimeWork { get; set; }
        public string sphereActivity { get; set; }
    }
}
